[package]
name = "tokay-compile"
version = "0.1.0"
edition = "2024"

[dependencies]
tokay = { path = "../..", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11"
