[package]
name = "tokay-run"
version = "0.1.0"
edition = "2024"

[dependencies]
tokay = { path = "../.." }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = { version = "2.0.1", features = ["serde"] }
