/*! Tokay builtin registry

THIS MODULE IS AUTOMATICALLY GENERATED BY BUILD.RS;
DON'T CHANGE THIS FILE MANUALLY, IT WILL GO AWAY!!!
*/
use crate::builtin::Builtin;

pub static BUILTINS: [Builtin; 40] = [
    Builtin {
        name: "Float",
        func: crate::value::token::tokay_token_float,
    },
    Builtin {
        name: "Ident",
        func: crate::value::token::tokay_token_ident,
    },
    Builtin {
        name: "Int",
        func: crate::value::token::tokay_token_int,
    },
    Builtin {
        name: "Word",
        func: crate::value::token::tokay_token_word,
    },
    Builtin {
        name: "addr",
        func: crate::value::value::Value::tokay_method_addr,
    },
    Builtin {
        name: "ast",
        func: crate::compiler::ast::tokay_function_ast,
    },
    Builtin {
        name: "ast_print",
        func: crate::compiler::ast::tokay_function_ast_print,
    },
    Builtin {
        name: "bool",
        func: crate::value::value::Value::tokay_method_bool,
    },
    Builtin {
        name: "chr",
        func: crate::builtin::tokay_function_chr,
    },
    Builtin {
        name: "dict",
        func: crate::value::dict::Dict::tokay_method_dict,
    },
    Builtin {
        name: "dict_len",
        func: crate::value::dict::Dict::tokay_method_dict_len,
    },
    Builtin {
        name: "dict_update",
        func: crate::value::dict::Dict::tokay_method_dict_update,
    },
    Builtin {
        name: "error",
        func: crate::error::tokay_function_error,
    },
    Builtin {
        name: "float",
        func: crate::value::value::Value::tokay_method_float,
    },
    Builtin {
        name: "float_ceil",
        func: crate::value::value::Value::tokay_method_float_ceil,
    },
    Builtin {
        name: "float_fract",
        func: crate::value::value::Value::tokay_method_float_fract,
    },
    Builtin {
        name: "float_trunc",
        func: crate::value::value::Value::tokay_method_float_trunc,
    },
    Builtin {
        name: "int",
        func: crate::value::value::Value::tokay_method_int,
    },
    Builtin {
        name: "list",
        func: crate::value::list::List::tokay_method_list,
    },
    Builtin {
        name: "list_add",
        func: crate::value::list::List::tokay_method_list_add,
    },
    Builtin {
        name: "list_iadd",
        func: crate::value::list::List::tokay_method_list_iadd,
    },
    Builtin {
        name: "list_len",
        func: crate::value::list::List::tokay_method_list_len,
    },
    Builtin {
        name: "list_pop",
        func: crate::value::list::List::tokay_method_list_pop,
    },
    Builtin {
        name: "list_push",
        func: crate::value::list::List::tokay_method_list_push,
    },
    Builtin {
        name: "ord",
        func: crate::builtin::tokay_function_ord,
    },
    Builtin {
        name: "print",
        func: crate::builtin::tokay_function_print,
    },
    Builtin {
        name: "repr",
        func: crate::builtin::tokay_function_repr,
    },
    Builtin {
        name: "str",
        func: crate::value::str::Str::tokay_method_str,
    },
    Builtin {
        name: "str_add",
        func: crate::value::str::Str::tokay_method_str_add,
    },
    Builtin {
        name: "str_byteslen",
        func: crate::value::str::Str::tokay_method_str_byteslen,
    },
    Builtin {
        name: "str_endswith",
        func: crate::value::str::Str::tokay_method_str_endswith,
    },
    Builtin {
        name: "str_join",
        func: crate::value::str::Str::tokay_method_str_join,
    },
    Builtin {
        name: "str_len",
        func: crate::value::str::Str::tokay_method_str_len,
    },
    Builtin {
        name: "str_lower",
        func: crate::value::str::Str::tokay_method_str_lower,
    },
    Builtin {
        name: "str_mul",
        func: crate::value::str::Str::tokay_method_str_mul,
    },
    Builtin {
        name: "str_replace",
        func: crate::value::str::Str::tokay_method_str_replace,
    },
    Builtin {
        name: "str_startswith",
        func: crate::value::str::Str::tokay_method_str_startswith,
    },
    Builtin {
        name: "str_substr",
        func: crate::value::str::Str::tokay_method_str_substr,
    },
    Builtin {
        name: "str_upper",
        func: crate::value::str::Str::tokay_method_str_upper,
    },
    Builtin {
        name: "type",
        func: crate::builtin::tokay_function_type,
    },
];
